In [2]:
import numpy as np

- numpy는 np.array 함수를 활용 > 배열 생성 >> ndarray
- np는 하나의 데이터 type만 : list와 가장 큰 차이
  (dynamic typing not supported)
- C의 array 사용하여 배열 생성

In [3]:
#array creation
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [10]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [11]:
a[0] is b[-1]

True

In [12]:
a = np.array(a, int)
type(a) # 객체
b = np.array(b)

np는 값을 할당
py는 주소값을 할당

연산 향상
https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

메모리 효율
https://www.slideshare.net/enthought/numpy-talk-at-siam

In [13]:
a[0] is b[-1]

False

RANK (0) : scalar
RANK (1) : vector
RANK (2) : matrix
RANK (3) : 3-tensor
RANK (n) : n-tensor

In [14]:
c = [[1, 2, 3], [4, 5, 6], [6, 7, 8]]
np.array(c).shape

(3, 3)

In [17]:
d = np.array([1, 4, 7, 9], float)
d.shape 
type(d.shape)  # > tuple

tuple


# reshape
: shape 크기 변경, element 갯수 동일

In [18]:
e = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(e).shape

(2, 4)

In [21]:
np.array(e).reshape(-1,2)
# 2만 지정하고 싶을 때,-1 넣어주면 알아서

# np.array(e).reshape(4,2) 와 같음

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.array(e).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
np.array(e).reshape(1, 8, 2)

ValueError: ignored

In [27]:
np.array(e).reshape(1, -8, 2)
# -8 => 4

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [20]:
e
# e 는 그대로
# 할당이 안되었으니

[[1, 2, 3, 4], [5, 6, 7, 8]]

# flatten
: reshape의 일종, 다차원을 1차원으로

In [30]:
f = [[[1, 2, 3, 4], [5, 6, 7, 8]], [[-1, -2, -3, -4], [-5, -6, -7, -8]]]    # (2, 2, 4) 
f = [[[1, 2, 3, 4], [5, 6, 7, 8]], [[-1, -2, -3, -4], [-5, -6, -7, -8]], [[0, 0, 0, 0], [1, 0, 0, 1]]]   # (3, 2, 4)
np.array(f).shape

(3, 2, 4)

In [32]:
np.array(f).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, -1, -2, -3, -4, -5, -6, -7, -8,  0,
        0,  0,  0,  1,  0,  0,  1])

In [33]:
f

[[[1, 2, 3, 4], [5, 6, 7, 8]],
 [[-1, -2, -3, -4], [-5, -6, -7, -8]],
 [[0, 0, 0, 0], [1, 0, 0, 1]]]

In [35]:
g = np.array(f).flatten()
g

array([ 1,  2,  3,  4,  5,  6,  7,  8, -1, -2, -3, -4, -5, -6, -7, -8,  0,
        0,  0,  0,  1,  0,  0,  1])

# Indexing 

In [36]:
h = np.array([[1, 2, 3], [4.5, 5, 6]], int)
h

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print('h[0, 0]', h[0, 0])
print('h[0][0]', h[0][0])

h[0, 0] 1
h[0][0] 1


In [40]:
h[0, 0] = 10.1
print(h)

[[10  2  3]
 [ 4  5  6]]


In [41]:
h[1][0] = 11.1
print(h)

[[10  2  3]
 [11  5  6]]


# Slicing

j [row 범위, column 범위]

https://www.slideshare.net/PyData/introduction-to-numpy

In [42]:
j = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
j

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
j[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [46]:
j[1, 1:3]
j[1, 1:3].shape

(2,)

In [45]:
j[1:3]

array([[ 6,  7,  8,  9, 10]])

In [47]:
j[:, -1]

array([ 5, 10])

In [48]:
j[:, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [49]:
j[:, ::3]

array([[1, 4],
       [6, 9]])

# 함수 생성 creation func

- arange

In [54]:
#list
list(range(0, 10, 3))

[0, 3, 6, 9]

In [56]:
k = np.arange(30)
type(k)

numpy.ndarray

In [55]:
list(range(0, 5, 0.5))

TypeError: ignored

In [52]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [53]:
# reshape 이랑 많이
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

- ones
- zeros
- empty : shape만 주어지고 비워진 ndarray (memory initialization X)

- ones_like
- zeros_like

In [57]:
test = np.arange(30).reshape(-1,6)
np.ones_like(test)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [60]:
np.empty(shape=(10,), dtype = int)
# garbage collection

array([           46416000,                   0,                   0,
                         0,     140381006069760, 7364851285506863154,
       7292503398809821741, 3257005467539158322, 3775761641249137203,
           140381848363576])

# identity & eye (시작값 설정)

In [61]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [62]:
np.identity(5)   # default : float

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.eye(N=3, M=5, dtype=np.int8)
# np.eye(N=3, M=5, dtype=int8)  # error

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

# diag
: 대각 행렬의 값을 추출

In [68]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)
np.diag(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [69]:
np.diag(matrix, k=1)

array([1, 5])

# random
- np.random.uniform.   균등분포
- np.random.normal    정규분포

In [70]:
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.99638466, 0.05071309, 0.9683258 , 0.6293986 , 0.38380327],
       [0.16081926, 0.59645657, 0.36811039, 0.06072271, 0.92240892]])

In [71]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.90277107,  1.8906822 ,  0.25081565,  1.74130692,  1.02517145],
       [-2.17925519,  1.0664421 ,  0.96914365,  0.9377195 ,  0.68434403]])

# Operation func : sum, axis